spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ezr
    username: postgres
    password: 5938240s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        query:
          in_clause_parameter_padding: true
#        generate_statistics: true ## When you want to check the performance
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  jackson:
server:
  port: 8081
origin:
  value:
    1: http://localhost:3001
#    default-property-inclusion: non_null