spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ezr
    username: postgres
    password: 5938240s
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        query:
          in_clause_parameter_padding: true
#        generate_statistics: true ## When you want to check the performance
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      log-condition-evaluation-delta: false
  mail:
    host: smtp.gmail.com
    username: sardoralien@gmail.com
    password: hmvnvqpooqbtommt
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
server:
  port: 8081

## for experiment purposes
origin:
  value:
    1: http://localhost:3001
#    default-property-inclusion: non_null

application:
  security:
    jwt:
      secret-key: 50645367566B59703373367638792F423F4528482B4D6251655468576D5A7134
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

